version: '3'

services:
  pia-wg-generator:    
    container_name: pia-wg-generator
    image: fbeilke/pia-wg-generator:latest
    environment:      
      - PIA_USER=p2259420
      - PIA_PASS=P9gjrgN3BY
      - REGIONS=br,de_berlin,denmark,france,de-frankfurt,nl_amsterdam,no,sweden,swiss,uk
      - UPDATE_INTERVAL=0 */12 * * *
      - CONFIG_DIR=/configs
      - DEBUG=0
    volumes:
      - /volume1/docker/pia-wireguard/generated_configs:/configs
    restart: unless-stopped
